# Constants
SCREEN_WIDTH = 600
SCREEN_HEIGHT = 800

# Physics
PIXELS_PER_METER = 30
GRAVITY = (0, -9.8)

# Player
PLAYER_SPRITE_WIDTH = 64
PLAYER_SPRITE_HEIGHT = 64
PLAYER_HITBOX_WIDTH = 1.0
PLAYER_HITBOX_HEIGHT = 2.0
PLAYER_MAX_SPEED = 8
JUMP_COOLDOWN = 75
JUMP_STRENGTH = 25

# Platforms
PLATFORM_WIDTH = 60
PLATFORM_HEIGHT = 10

# Ground
GROUND_WIDTH = 50
GROUND_HEIGHT = 0.25